// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3W3A4pdULCh-_R0J40pDcoPKysmVpfm0',
    appId: '1:744237594494:web:720655ec3875345357252f',
    messagingSenderId: '744237594494',
    projectId: 'agriproject-bdd22',
    authDomain: 'agriproject-bdd22.firebaseapp.com',
    storageBucket: 'agriproject-bdd22.appspot.com',
    measurementId: 'G-NHN3FELGJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh7yXDKcAjW12dRGScXAK6MuWQ7Li3qxc',
    appId: '1:744237594494:android:2f8987aeb2c8102b57252f',
    messagingSenderId: '744237594494',
    projectId: 'agriproject-bdd22',
    storageBucket: 'agriproject-bdd22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkO8usS1ZF8QdpppDWxePHCGQAcmwYRMY',
    appId: '1:744237594494:ios:32108f0746f7a46257252f',
    messagingSenderId: '744237594494',
    projectId: 'agriproject-bdd22',
    storageBucket: 'agriproject-bdd22.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );
}
